services:
  operator:
    build:
      context: ./operator
      dockerfile: Dockerfile
    image: sguldemond/goblin-operator:latest

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    image: sguldemond/goblin-scout:latest

  telegram:
    build:
      context: ./telegram
      dockerfile: Dockerfile
    image: sguldemond/goblin-horn:latest
