// Command rbacgen writes the kubebuilder RBAC markers implied by
// detection.Envelope.
//
// The operator must hold get/list/watch on every kind it watches, and it
// watches exactly the envelope. Keeping those two in step by hand is the kind
// of thing that silently rots: adding a kind compiles, validates, starts a
// watch, and then dies on a 403 at runtime. Generating the markers makes the
// envelope the only place to edit.
//
// Run via `go generate ./...`, then `make manifests` to fold the markers into
// config/rbac/role.yaml.
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/sguldemond/goblin/internal/detection"
)

const outPath = "zz_generated_rbac.go"

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "rbacgen: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	// One marker per API group, resources sorted, so the output is stable and
	// diffs only when the envelope actually changes.
	byGroup := map[string][]string{}
	for _, t := range detection.Envelope {
		byGroup[t.GVK.Group] = append(byGroup[t.GVK.Group], t.Resource)
	}

	groups := make([]string, 0, len(byGroup))
	for g := range byGroup {
		groups = append(groups, g)
	}
	sort.Strings(groups)

	var b strings.Builder
	b.WriteString("// Code generated by internal/rbacgen. DO NOT EDIT.\n")
	b.WriteString("// Source: detection.Envelope in envelope.go\n\n")
	b.WriteString("package detection\n\n")
	b.WriteString("// The operator watches every kind in the Envelope, so it needs standing\n")
	b.WriteString("// read access to each of them.\n")

	for _, g := range groups {
		resources := byGroup[g]
		sort.Strings(resources)
		resources = slicesCompact(resources)
		fmt.Fprintf(&b, "// +kubebuilder:rbac:groups=%s,resources=%s,verbs=get;list;watch\n",
			quoteGroup(g), strings.Join(resources, ";"))
	}

	return os.WriteFile(outPath, []byte(b.String()), 0o644)
}

// quoteGroup renders the core API group the way kubebuilder markers expect it.
func quoteGroup(g string) string {
	if g == "" {
		return `""`
	}
	return g
}

func slicesCompact(s []string) []string {
	out := s[:0]
	var prev string
	for i, v := range s {
		if i == 0 || v != prev {
			out = append(out, v)
		}
		prev = v
	}
	return out
}
