apiVersion: ops.goblinoperator.io/v1alpha1
kind: Incident
metadata:
  name: incident-sample
  namespace: default
spec:
  targetRef:
    apiVersion: v1
    kind: Pod
    name: sample-pod
    namespace: default
  trigger: OOMKilled
