// Code generated by internal/rbacgen. DO NOT EDIT.
// Source: detection.Envelope in envelope.go

package detection

// The operator watches every kind in the Envelope, so it needs standing
// read access to each of them.
// +kubebuilder:rbac:groups="",resources=pods,verbs=get;list;watch
// +kubebuilder:rbac:groups=apps,resources=deployments;replicasets,verbs=get;list;watch
